[build]
  publish = "dist"
  command = "npm run build"
  environment = { NODE_VERSION = "18" }

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]