[build]
  publish = "dist"
  command = "npm install && npm run build"
  environment = { NODE_VERSION = "18" }

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["nodemailer"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]